spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: admin
    password: admin123

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${ spring.application.instance_id:${random.value} }

mq:
  queues:
    emissao-cartoes: emissao-cartoes
