spring:
  application:
    name: mscartoes
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #  defaultZone: http://admin:admin@localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${ spring.application.instance_id:${random.value} }

mq:
  queues:
    emissao-cartoes: emissao-cartoes
